Update release-apk.yml

diff --git a/.github/workflows/release-apk.yml b/.github/workflows/release-apk.yml
--- a/.github/workflows/release-apk.yml
+++ b/.github/workflows/release-apk.yml
@@ -1,10 +1,9 @@
-# From https://github.com/ni554n/apk-builder-action
-# guide https://github.com/marketplace/actions/automated-build-android-app-with-github-action
-name: Build Android APK
+name: Build, Test, and Release Android APK
 run-name: ${{ github.event.inputs.repository }}:${{ github.event.inputs.taskName }}
 env:
   # The name of the main module repository
   main_project_module: workspace
+  app_directory: ""
   
 on:
   workflow_dispatch:
@@ -16,26 +15,28 @@ on:
       jdkVersion:
         description: "OpenJDK version to use: 8 / 11 / 17 etc."
         required: false
-        default: "8"
+        default: "17"
       taskName:
         description: "build.gradle task name: assemble[Flavor]Debug"
         required: false
         default: "assembleDebug"
-      appDirectory:
-        description: "Default directory where build.gradle located [/your directory]"
-        required: false
-        default: ""
+      release:
+        description: "Whether to release the APK (true/false)"
+        required: true
+        default: "false"
+      yourAppName:
+        description: "Name of your application"
+        required: true
 
 jobs:
   build:
-    runs-on: ubuntu-latest # Android SDK is built-in in this image
-        
+    runs-on: ubuntu-latest
+
     steps:
 
-      # Set Current Date As Env Variable
       - name: Set Current DATE
         run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
-        
+
       - name: Setup JDK
         uses: actions/setup-java@v3
         with:
@@ -45,16 +46,81 @@ jobs:
       - name: Clone project
         run: git clone --depth=1 ${{ github.event.inputs.repository }} ${{ env.main_project_module }}
 
+      - name: Find appDirectory
+        run: |
+          # Find the directory containing the build.gradle file
+          export app_directory=$(find ./${{ env.main_project_module }} -name "build.gradle" -exec dirname {} \; | head -n 1)
+          echo "::set-env name=app_directory::$app_directory"
+
+      - name: Update dependencies
+        working-directory: ${{ env.app_directory }}
+        run: ./gradlew --refresh-dependencies
+
       - name: Build APK
-        working-directory: ./${{ env.main_project_module }}${{ github.event.inputs.appDirectory }}
+        working-directory: ${{ env.app_directory }}
         run: |
           if [ ! -f "gradlew" ]; then gradle wrapper; fi
           chmod +x gradlew
           ./gradlew ${{ github.event.inputs.taskName }} --stacktrace
 
+      - name: Run tests
+        working-directory: ${{ env.app_directory }}
+        run: ./gradlew test connectedAndroidTest --stacktrace
+
+      - name: Calculate checksum
+        id: checksum
+        run: |
+          cd ${{ env.app_directory }}/app/build/outputs/apk/
+          shasum -a 256 *.apk | awk '{print $1}' > apk_checksum.txt
+          echo "::set-output name=checksum::$(cat apk_checksum.txt)"
+
       - name: Upload the APK artifact with 1 day retention
+        if: always()
         uses: actions/upload-artifact@v3
         with:
-          path: ${{ env.main_project_module }}${{ github.event.inputs.appDirectory }}/app/build/outputs/apk/
+          path: ${{ env.app_directory }}/app/build/outputs/apk/
           name: apk-debug [${{ env.date_today }}]
           retention-days: 1
+
+      - name: Run lint checks
+        working-directory: ${{ env.app_directory }}
+        run: ./gradlew lintDebug --console=plain --max-warnings 0 || echo "Lint found issues"
+
+      - name: Attempt to fix lint issues
+        if: ${{ github.event.inputs.release == 'true' }}
+        working-directory: ${{ env.app_directory }}
+        run: ./gradlew lintFixDebug --console=plain --max-warnings 0 || echo "Failed to fix lint issues"
+
+      - name: Create Release
+        if: ${{ github.event.inputs.release == 'true' }}
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+        with:
+          tag_name: v1.0.0  # Replace with your desired tag name
+          release_name: Release v1.0.0  # Replace with your desired release name
+          draft: false
+          prerelease: false
+
+      - name: Upload Release Asset
+        if: ${{ github.event.inputs.release == 'true' }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ env.app_directory }}/app/build/outputs/apk/*.apk
+          asset_name: ${{ github.event.inputs.yourAppName }}-${{ github.event.inputs.taskName }}-${{ env.date_today }}.apk
+          asset_content_type: application/vnd.android.package-archive
+
+      - name: Upload Checksum as Release Asset
+        if: ${{ github.event.inputs.release == 'true' }}
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ env.app_directory }}/app/build/outputs/apk/apk_checksum.txt
+          asset_name: ${{ github.event.inputs.yourAppName }}-${{ github.event.inputs.taskName }}-${{ env.date_today }}-checksum.txt
+          asset_content_type: text/plain
